baseURL = "http://example.org/"
title = "MobyTrip"
languageCode = "zh-CN"
copyright = "Copyright right infomation."
themesdir = "themes"
theme = "hugo_eiio"
Paginate=15 
PaginatePath="page"
pygmentsuseclasses = true
disqusShortname = "user id"
googleAnalytics='google analytics code'
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Best hotels in Istanbul"
  subDescription = "Enter your dates and choose from 2709 hotels, apartments and more!"
  author = "your name"
  github ="github username"
  securityPolicy = false #disable https content security policy
  footerRight="Your tips content" #footer right content
  addthisID="addthis.com sharder plugin id"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

